<footer>
        <div class="footer-class">
            <div class="foot-container">




                <div class="footer-horizontal">



                    <div class="footer-vertical">
                        <a href="index.php"><img src="images/logo.png" alt="logo"></a>
                        <div>
                            <h4>Useful Links</h4>
                            <ul>
                                <li><a href="about.php">About me</a></li>
                                <li><a href="jobpostform.php">Posting a job</a></li>
                                <li><a href="searchjobform.php">Search for jobs</a></li>
                                

                            </ul>
                        </div>


                        

                    </div>

                    <p>My Email: 104788737@student.swin.edu.au</p>
                    <p>I declare that this assignment is my individual work. I have not worked collaboratively, nor have I copied from any other student’s work or from any other source.</p>



                </div>


            </div>

        </div>
    </footer>