
        <div class="navigationbar">
            <nav>
                <a href="index.php"><img src="images/logo.png" alt="Logo" class="logo"></a>
                
                <div class="header-nav">
                    <ul>
                        <li><a href="index.php">Home</a></li>
                        <li><a href="searchjobprocess.php">Jobs</a></li>
                        <li><a href="about.php">About us</a></li>
                        <li><a href="jobpostform.php">Post a job</a></li>
                        <li class="last"><a href="searchjobform.php">Search</a></li>
                        
                    </ul>
                </div>
            </nav>
        </div>
